// <auto-generated />
using System;
using BILLETERACRIPTOMONEDASBACKEND.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BilleteraCriptomonedasBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706193142_MigracionClienteModificado")]
    partial class MigracionClienteModificado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("BILLETERACRIPTOMONEDASBACKEND.Models.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bitcoin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ethereum")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("USDT")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .IsUnique();

                    b.ToTable("Billetera");
                });

            modelBuilder.Entity("BILLETERACRIPTOMONEDASBACKEND.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BILLETERACRIPTOMONEDASBACKEND.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CryptoAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("CryptoCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MoneySpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreCliente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("BILLETERACRIPTOMONEDASBACKEND.Models.Billetera", b =>
                {
                    b.HasOne("BILLETERACRIPTOMONEDASBACKEND.Models.Cliente", "Cliente")
                        .WithOne("Billetera")
                        .HasForeignKey("BILLETERACRIPTOMONEDASBACKEND.Models.Billetera", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BILLETERACRIPTOMONEDASBACKEND.Models.Cliente", b =>
                {
                    b.Navigation("Billetera");
                });
#pragma warning restore 612, 618
        }
    }
}
